name: iOS build (macOS)

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-15
    env:
      TOOLCHAINS: swift
      XT_SIGNING: off
    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1"

      - run: brew update
      - run: brew install xtool-org/tap/xtool

      - name: Select Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer

      - name: Build app
        run: |
          export SDKROOT=$(xcrun --sdk iphonesimulator --show-sdk-path)
          make build
