# .github/workflows/ios-build.yml
name: iOS build on macOS

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install xtool
        run: brew install xtool-org/tap/xtool
      - run: make build 
