name: iOS build (macOS)

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-15
    env:
      XT_SIGNING: off
    steps:
      - uses: actions/checkout@v4

      - run: brew update
      - run: brew install xtool-org/tap/xtool

      - run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - run: make build