name: iOS build (macOS)

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-15
    env:
      TOOLCHAINS: swift
      XT_SIGNING: off
    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1"

      - run: brew update
      - run: brew install xtool-org/tap/xtool

      - name: Select Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer

      - name: Build app
        run: |
          export SDKROOT=$(xcrun --sdk iphonesimulator --show-sdk-path)
          make build

      - name: Verify build artifacts
        run: |
          echo "Checking build artifacts..."
          if [ -d "xtool/JustAMap.app" ]; then
            echo "✓ App bundle found at xtool/JustAMap.app"
            echo "App bundle contents:"
            ls -la xtool/JustAMap.app/
            echo "App executable size:"
            ls -lh xtool/JustAMap.app/JustAMap
          else
            echo "✗ App bundle not found at expected location"
            echo "Contents of xtool directory:"
            ls -la xtool/ || echo "xtool directory not found"
            exit 1
          fi
