# .github/workflows/ios-build.yml
name: iOS build (macOS trunk)

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-14

    env:
      TOOLCHAINS: swift
    steps:
      - uses: actions/checkout@v4

      - name: Set up Swift trunk
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: development

      - name: Install xtool
        run: |
          brew update
          brew install xtool-org/tap/xtool

      - name: Build with xtool
        run: make build
