name: iOS build and test (macOS)

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-15
    env:
      TOOLCHAINS: swift
      XT_SIGNING: off
    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1"

      - run: brew update
      - run: brew install xtool-org/tap/xtool

      - name: Select Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer

      - name: Run tests
        run: |
          export SDKROOT=$(xcrun --sdk iphonesimulator --show-sdk-path)
          make test || exit 1

      - name: Build app
        run: |
          set -e
          export SDKROOT=$(xcrun --sdk iphonesimulator --show-sdk-path)
          make build || exit 1

      - name: Verify build artifacts
        run: |
          echo "Checking build artifacts..."
          if [ -d "xtool/JustAMap.app" ]; then
            echo "✓ App bundle found at xtool/JustAMap.app"
            echo "App bundle contents:"
            ls -la xtool/JustAMap.app/
            echo "App executable size:"
            ls -lh xtool/JustAMap.app/JustAMap
          else
            echo "✗ App bundle not found at expected location"
            echo "Contents of xtool directory:"
            ls -la xtool/ || echo "xtool directory not found"
            exit 1
          fi

      - name: Comment @claude on PR failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            const workflowRun = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            
            const comment = `@claude The CI has failed on this PR. Please check the [workflow run](${workflowRun}) and help fix the issues.
            
            <details>
            <summary>Failed Workflow Details</summary>
            
            - **Workflow**: ${context.workflow}
            - **Run ID**: ${context.runId}
            - **Run Number**: ${context.runNumber}
            - **Event**: ${context.eventName}
            - **SHA**: ${context.sha}
            
            </details>`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment
            });
